- hosts: undercloud
  tasks:
  - name: grab auth data from openstackrc file and publish it as YAML
    vars:
        overcloud_rc: ~/overcloudrc.v3
    shell: |
        source {{ overcloud_rc }}
        echo "
        auth_url: $OS_AUTH_URL
        username: $OS_USERNAME
        password: $OS_PASSWORD
        project_name: ${OS_PROJECT_NAME:-$OS_TENANT_NAME}
        "
        if [ -n "$OS_PROJECT_DOMAIN_NAME" ]; then
            echo "project_domain_name: $OS_PROJECT_DOMAIN_NAME"
        fi
        if [ -n "$OS_USER_DOMAIN_NAME" ]; then
            echo "user_domain_name: $OS_USER_DOMAIN_NAME"
        fi
    register: creds
  - set_fact:
      os_creds: "{{ creds.stdout | from_yaml }}"
      
  - set_fact: 
      env:    
        OS_AUTH_TYPE: password
        OS_AUTH_URL: "{{ os_creds.auth_url }}"
        OS_CLOUDNAME: overcloud
        OS_IDENTITY_API_VERSION: 3
        OS_NO_CACHE: True
        OS_PASSWORD: "{{ os_creds.password }}"
        OS_PROJECT_DOMAIN_NAME: Default
        OS_PROJECT_NAME: "{{ os_creds.project_name }}"
        OS_USERNAME: "{{ os_creds.username }}"
        OS_USER_DOMAIN_NAME: Default
