# RHELOSP-20048
- include: auth.yml
- hosts: control
  tasks:
  - name: Check if rbd-mirror is installed
    include: roles/rbd-mirroring/is_rbd_mirror_service_installed.yml

  - name: check that chep-rbd-mirror service is started
    include: roles/rbd-mirroring/is_ceph_rdb_mirror_service_started.yml

#TODO: use pacemaker_cluster
#  - name: get cluster state
#    pacemaker_cluster: state=online
#    node: all # todo: chec which node
# create a volume 
- hosts: undercloud-0
  vars:
    ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
  tasks:
  - name: create 4g test volume
    include: roles/ops/volume_create.yml

# check that the volume was created with exclusive-lock
- hosts: ceph-0
  become: true
  tasks:
  - name: verify image on ceph
    rbd: action=info image=volume-{{ hostvars['undercloud-0']['testvolume_fact'].volume.id }} pool=volumes
    register: volumeinfo
    failed_when: '"exclusive-lock" not in volumeinfo.image.features'
  - debug: var=volumeinfo

# remove the volume we've created
- hosts: undercloud-0
  vars: 
    ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
  tasks:
  - name: remove 4g test volume
    include: roles/ops/volume_remove.yml

