- include: auth.yml
- hosts: undercloud-0
  vars: 
    ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
  environment: "{{ env }}"
  tasks:
  - include_vars:
      file: images.yml
      name: images
  - name: download cirros image
    get_url:
      url: "{{ images.cirros_url }}"
      dest: /tmp/cirros-0.3.4-x86_64-disk.img

  - name: upload an image
    os_image:
      auth: "{{ os_creds }}"
      name: cirros
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /tmp/cirros-0.3.4-x86_64-disk.img
      kernel: cirros-vmlinuz
      ramdisk: cirros-initrd
      properties:
        cpu_arch: x86_64
        distro: ubuntu
    register: cirrosimage
  - set_fact: testimage={{ cirrosimage }}

  - name: create empty volume
    os_volume:
      auth: "{{ os_creds }}"
      state: present
      size: 1
      display_name: volume1

  - name: create volume from image
    os_volume:
      auth: "{{ os_creds }}"
      state: present
      image: "{{ testimage.id }}"
      size: 2
      display_name: volume2
    register: testvolume
  - set_fact: testvolume_fact={{ testvolume }}


  - name: create volume snapshot
    shell: openstack volume snapshot create --volume {{ hostvars['undercloud-0']['testvolume_fact'].volume.id }} test_snap -f json
    register: snapshot
  - set_fact: snapshot_fact={{ snapshot.stdout }}

  - name: create flavor 
    os_nova_flavor:
      auth: "{{ os_creds }}"
      state: present
      name: tiny
      ram: 1024
      vcpus: 1
      disk: 10

  - name: lunch instance from volume2
    os_server:
      name: test_vm1
      state: present
      auth: "{{ os_creds }}"
      image: "{{ testimage.id }}"
      flavor: tiny
      volumes:
      - "volume1"
      - "volume2"

  - name: remove instance
    os_server:
      name: test_vm1
      state: absent
      auth: "{{ os_creds }}"

  - name: delete snapshot
    shell: openstack volume snapshot delete {{ hostvars['undercloud-0']['snapshot_fact'].id }}
  
  - name: delete empty volume
    os_volume:
      auth: "{{ os_creds }}"
      state: absent
      display_name: volume1

  - name: delete volume from image
    os_volume:
      auth: "{{ os_creds }}"
      state: absent
      display_name: volume2

  - name: delete image
    os_image:
      auth: "{{ os_creds }}"
      name: cirros
      state: absent

  - name: create flavor 
    os_nova_flavor:
      auth: "{{ os_creds }}"
      state: absent
      name: tiny
