- include: auth.yml
- hosts: undercloud-0
  vars: 
    ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
  tasks:
  - include_vars:
      file: images.yml
      name: images
  - name: download cirros image
    get_url:
      url: "{{ images.cirros_url }}"
      dest: /tmp/cirros-0.3.4-x86_64-disk.img

  - name: upload image to glance
    os_image:
      auth: "{{ os_creds }}"
      name: cirros
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /tmp/cirros-0.3.4-x86_64-disk.img
      kernel: cirros-vmlinuz
      ramdisk: cirros-initrd
      properties:
        cpu_arch: x86_64
        distro: ubuntu
    register: cirrosimage
  - set_fact: testvolume={{ cirrosimage }}
  - debug: var=testvolume

- hosts: ceph-0
  become: true  
  tasks:
  - name: verify image on ceph
    rbd_image_facts: name={{ hostvars['undercloud-0']['testvolume'].id }} pool=images
    register: volumeinfo

- hosts: undercloud-0
  vars: 
    ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
  tasks:  
  - name: remove cirros image
    os_image:
      auth: "{{ os_creds }}"
      state: absent
      name: cirros

